# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: example.com
  secret_key_base: 2be291ce1ad01891e9e73478b589b0ef0aa6502db231e7e7b19877f4ac923fb1c108f8c3fde5599503c9593946148734f1a292149048fbe7757a0beed32b4dda

test:
  domain_name: example.com 
  secret_key_base: 8cedbe13447166fbcc390a9fd030db7b00a326807438d6e72df014572a4201dd19e75d0254c39d447c593976de10a84b84867c1a2b4765a496c852a88a42ccf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
